name: Pruebas unitarias

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Usa Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Instala dependencias
        run: npm install
      - name: Ejecuta pruebas unitarias
        run: npm test
        